"""
Generate training data for COBOL tutor chatbot
Generates questions covering COBOL structure, debugging, 
mainframe concepts, and functions for model training
"""

def load_example_file(filename):
    """Load example file contents and return as string wrapped in markdown code blocks"""
    try:
        with open(f'code_examples/{filename}', 'r') as f:
            content = f.read()
            # Detect code type based on filename
            if 'jcl' in filename.lower():
                return f"```jcl\n{content}\n```"
            else:
                return f"```cobol\n{content}\n```"
    except FileNotFoundError:
        return ""
    except Exception as e:
        return ""

def generate_cobol_structure_qa():
    """Generate questions about COBOL program structure"""
    return [
        {"text": f"Q: What are the four divisions of a COBOL program?\nA: The four divisions of a COBOL program are:\n1. IDENTIFICATION DIVISION - Contains program metadata like program name and author\n2. ENVIRONMENT DIVISION - Describes the hardware and files used\n3. DATA DIVISION - Defines variables and data structures\n4. PROCEDURE DIVISION - Contains the actual program logic and processing steps"},
        {"text": f"Q: What goes in the IDENTIFICATION DIVISION?\nA: The IDENTIFICATION DIVISION must be the first division in each COBOL source program, factory definition, object definition, and method definition. The identification division names the program, class, or method and identifies the factory definition and object definition. The IDENTIFICATION DIVISION can include the date a program, class, or method was written, the date of compilation, and other such documentary information.\n\nHere is an example:\n\n{load_example_file('example_ID_DIV')}"},
        {"text" : f"Q: Can you write me an example of a  IDENTIFICATION DIVISION?\n A: Sure! Here is an example of an  IDENTIFICATION DIVISION in a COBOL program:\n\n{load_example_file('example_ID_DIV')}\n\n"},
        {"text": f"Q: What is the  ENVIRONMENT DIVISION?\nA: The Environment Division has two sections: The Configuration Section and the Input-Output Section.\n The Configuration Section is optional. When specified, it can describe the computer on which the source program is compiled and the computer on which the object program is executed. However, the Configuration Section must not be specified in a nested program. The entries specified in the Configuration Section of a program apply to all programs contained within that program as well as addition function\n The Input-Output Section defines each file, identifies its external storage medium, assigns the file to one or more input/output devices, and specifies information needed for transmission of data between the external medium and the COBOL program.\n."},
        {"text": f"Q: What is the Configuration Section?.\n A: The Configuration Section is optional. When specified, it can describe the computer on which the source program is compiled and the computer on which the object program is executed. However, the Configuration Section must not be specified in a nested program. The entries specified in the Configuration Section of a program apply to all programs contained within that program. In addition, the Configuration Section can:\nRelate IBM®-defined environment-names to user-defined mnemonic names.\nSpecify the collating sequence.\nSpecify a single or multiple character currency string and a substitute character for the currency sign.\nInterchange the functions of the comma and the period in PICTURE clauses and numeric literals.\nRelate alphabet-names to character sets or collating sequences.\nRelate class names to sets of characters.\nSpecify the type of linkage to be made on a CALL, CANCEL, or SET… ENTRY statement.\nSpecify the default formats for a date or time data type."},
        {"text": f"Q: What is the Input-Output Section?.\n A: The Input-Output Section defines each file, identifies its external storage medium, assigns the file to one or more input/output devices, and specifies information needed for transmission of data between the external medium and the COBOL program.\nThe Input-Output section of the Environment Division contains two paragraphs:\nFILE-CONTROL paragraph\nI-O-CONTROL paragraph."},
        {"text": f"Q: What is the FILE-CONTROL Section of the Input-Output Section?\n A: The FILE-CONTROL paragraph associates each file in the COBOL program with an external medium, and specifies file organization, access mode, and other information.\n\nThe FILE-CONTROL paragraph begins with the word 'FILE-CONTROL', followed by a separator period. It must contain one and only one entry for each file described in an FD or SD entry in the Data Division. Within each entry, the SELECT clause must appear first. The other clauses may appear in any order.\n\nEach data-name must appear in a Data Division data description entry. Each data-name can be qualified but cannot be subscripted or indexed.\n\nThe FILE-CONTROL paragraph has five formats:\nFormat 1 - Sequential Files\nFormat 2 - Relative Files\nFormat 3 - Indexed Files\nFormat 4 - Sort or Merge Files\nFormat 5 - Transaction Files."},
        {"text": f"Q: What is the I-O-CONTROL Section of the Input-Output Section?\n A: The I-O-CONTROL paragraph of the INPUT-OUTPUT SECTION specifies the storage areas to be shared by different files. This paragraph is optional in a COBOL program.\n\nThe keyword I-O-CONTROL may appear only once, at the beginning of the paragraph. The word I-O-CONTROL must begin in Area A, and must be followed by a separator period.\n\nEach clause within the paragraph may be separated from the next by a separator comma or a separator semicolon. The order in which I-O-CONTROL paragraph clauses are written is not significant. The I-O-CONTROL paragraph ends with a separator period.\n\nThe I-O-CONTROL paragraph has three formats:\nFormat 1 - Sequential Files\nFormat 2 - Indexed and Relative Files\nFormat 3 - Sort or Merge Files"},
        {"text": f"Q: Can you write me an example of a ENVIRONMENT DIVISION?\n A: Sure! Here is an example of an ENVIRONMENT DIVISION in a COBOL program:\n\n{load_example_file('example_ENV_DIV')}\n\n"},
        {"text": f"Q: What is the DATA DIVISION?.\n A: Each section in the DATA DIVISION has a specific logical function within a COBOL program, object definition, factory definition, or method and can be omitted when that logical function is not needed. If included, the sections must be written in the order shown. The DATA DIVISION is optional. It has the following sections: \nFILE SECTION\nThe FILE SECTION defines the structure of data files. The FILE SECTION must begin with the header FILE SECTION, followed by a separator period.\nWORKING-STORAGE SECTION\nThe WORKING-STORAGE SECTION describes data records that are not part of data files but are developed and processed by a program or method. The WORKING-STORAGE SECTION also describes data items whose values are assigned in the source program or method and do not change during execution of the object program.\nLOCAL-STORAGE SECTION\nThe LOCAL-STORAGE SECTION defines storage that is allocated and freed on a per-invocation basis.\nLINKAGE SECTION\nThe LINKAGE SECTION describes data made available from another program or method."},
        {"text": f"Q: Can you write me an example of a DATA DIVISION?\n A: Sure! Here is an example of a DATA DIVISION in a COBOL program:\n\n{load_example_file('example_DATA_DIV')}\n\n"},
        {"text": f"Q: What is the PROCEDURE DIVISION?.\n A: The Procedure Division is optional in a COBOL source program. The Procedure Division consists of optional declaratives, and procedures that contain sections and/or paragraphs, sentences, and statements.\n\nThe structure of the Procedure Division is as follows:\nFormat 1 - with Sections and Paragraphs\nFormat 2 - with Paragraphs Only.\nExecution begins with the first statement in the Procedure Division, excluding declaratives. Statements are executed in the order in which they are presented for compilation, unless the statement rules dictate some other order of execution.\n\nThe Procedure Division ends at the END PROGRAM header, before the beginning of the next COBOL source program, or at the physical end of the program. The physical end of the program is the physical position in a source program after which no further statements appear."},
        {"text": f"Q: What happens in the PROCEDURE DIVISION?.\n A: The Procedure Division is where the actual processing logic of a COBOL program is implemented. It contains the executable statements that perform the tasks defined by the program. This is where you write the code to manipulate data, control program flow, and interact with files and other resources. The Procedure Division can include sections and paragraphs that help organize the code into logical blocks, making it easier to read and maintain."},
        {"text": f"Q: Can you write me an example of a PROCEDURE DIVISION?\n A: Sure! Here is an example of a PROCEDURE DIVISION in a COBOL program:\n\n{load_example_file('example_PROC_DIV')}\n\n"},
        {"text": f"Q: What is a paragraph in COBOL?.\n A: In COBOL, a paragraph is a logical subdivision of code within a section or a division, acting as a labeled block of one or more sentences (statements) that perform a specific function. They are a key structural element, particularly in the PROCEDURE DIVISION, to organize program logic."},
        {"text": f"Q: What is a sentence in COBOL?\n A: In COBOL, a sentence is a sequence of one or more statements, appearing in the PROCEDURE DIVISION, that terminates with a period. It is considered the smallest executable unit in a program's logic flow, forming a complete command."},
        {"text": f"Q: What is a PIC or PICTURE clause in COBOL?\n A: The PICTURE clause specifies the general characteristics and editing requirements of an elementary item. PIC is an abbreviation for PICTURE and has the same meaning. The PICTURE clause can be specified only at the elementary level and defines the size, type, and editing format of data fields in your program."},
        {"text": f"Q: When is the PICTURE clause required in COBOL?\n A: The PICTURE clause must be specified for every elementary item except the following: Index data items, the subject of the RENAMES clause, items described with USAGE POINTER, USAGE FUNCTION-POINTER, USAGE PROCEDURE-POINTER, or USAGE OBJECT REFERENCE, and internal floating-point data items. In these cases, use of the PICTURE clause is prohibited."},
        {"text": f"Q: What are the different USAGE types for PICTURE clauses?\n A: The USAGE clause affects how character positions in a PICTURE clause are interpreted. The main types are: DISPLAY (Alphanumeric, 1 byte per character), DISPLAY-1 (DBCS, 2 bytes per character), NATIONAL (National characters, 2 bytes per character), and UTF-8 (1 to 4 bytes per character). All other usages use conceptual character positions."},
        {"text": f"Q: What does the 9 symbol mean in a PICTURE clause?\n A: The 9 symbol represents a numeric character position that contains a numeral. Each 9 specifies one decimal digit in the value of the item. For usages DISPLAY and NATIONAL, each 9 is counted as one character position in the size of the data item."},
        {"text": f"Q: What does the S symbol mean in a PICTURE clause?\n A: The S symbol is an indicator of the presence of an operational sign, which indicates whether the value of an item is positive or negative. The S is not counted in the size of the elementary item, unless an associated SIGN clause specifies the SEPARATE CHARACTER phrase, which would be counted as one character position."},
        {"text": f"Q: What does the V symbol mean in a PICTURE clause?\n A: The V symbol is an indicator of the location of the assumed decimal point. It does not represent a character position in the item. When the assumed decimal point is to the right of the rightmost symbol in the string, the V is redundant. It is not counted in the size of the elementary item."},
        {"text": f"Q: What does the P symbol mean in a PICTURE clause?\n A: The P symbol represents an assumed decimal scaling position, used to specify the location of an assumed decimal point when the point is not within the number that appears in the data item. P is not counted in the size of the data item, but scaling position characters are counted in determining the maximum number of digit positions in numeric-edited items or in items used as arithmetic operands."},
        {"text": f"Q: What does the A symbol mean in a PICTURE clause?\n A: The A symbol represents a character position that can contain only a letter of the Latin alphabet or a space. Each 'A' is counted as one character position in the size of the data item."},
        {"text": f"Q: What does the X symbol mean in a PICTURE clause?\n A: The X symbol represents a character position that can contain any allowable character from the alphanumeric character set of the computer. Each 'X' is counted as one character position in the size of the data item."},
        {"text": f"Q: What does the Z symbol mean in a PICTURE clause?\n A: The Z symbol is a leading numeric character position. When that position contains a zero, a space character replaces the zero. This is used for editing numeric values to suppress leading zeros. Each 'Z' is counted as one character position in the size of the data item."},
        {"text": f"Q: What editing symbols can I use in a PICTURE clause for signs and currency?\n A: You can use several editing symbols for sign control and currency: + and - for sign display, CR and DB for credit/debit indicators, and cs (any currency symbol like $) for currency sign values. The default currency symbol is the dollar sign ($). Each character used in these editing symbols is counted as one character position in the size of the data item."},
        {"text": f"Q: What does the asterisk (*) symbol mean in a PICTURE clause?\n A: The asterisk (*) is a check protect symbol and represents a leading numeric character position. When that position contains a zero, an asterisk is inserted in its place. This is used to protect or highlight fields such as check amounts. Each asterisk is counted as one character position in the size of the item."},
        {"text": f"Q: What do the / , and . symbols mean in a PICTURE clause?\n A: These are editing symbols for formatting: the / symbol inserts a slash character, the , symbol inserts a comma, and the . symbol represents the decimal point for alignment purposes and inserts a period. Each of these symbols is counted as one character position in the size of the data item."},
        {"text": f"Q: What does the 0 symbol mean in a PICTURE clause?\n A: The 0 symbol represents a character position into which the numeral zero is inserted. It is used when you want to force a zero to appear in a specific position of the data value. Each zero is counted as one character position in the size of the data item."},
        {"text": f"Q: What do B, E, G, N, and U symbols mean in a PICTURE clause?\n A: These symbols handle special character types: B inserts spaces (alphanumeric, DBCS, or national depending on USAGE), E marks the start of the exponent in floating-point items, G is a DBCS character position, N is a DBCS or national character position depending on compiler options and USAGE, and U is a UTF-8 character position where USAGE UTF-8 is assumed. Each is counted as one character position."},
    ]

def generate_mainframe_concepts_qa():
    """Generate questions about mainframe concepts"""
    return [
        {"text": "Q: What is a dataset in mainframe systems?\n A: The term data set refers to a file that contains one or more records. The record is the basic unit of information used by a program running on z/OS.\n\nAny named group of records is called a data set. Data sets can hold information such as medical records or insurance records, to be used by a program running on the system. Data sets are also used to store information needed by applications or the operating system itself, such as source programs, macro libraries, or system variables or parameters. For data sets that contain readable text, you can print them or display them on a console (many data sets contain load modules or other binary data that is not really printable). Data sets can be cataloged, which permits the data set to be referred to by name without specifying where it is stored.\n\nIn simplest terms, a record is a fixed number of bytes containing data. Often, a record collects related information that is treated as a unit, such as one item in a database or personnel data about one member of a department. The term field refers to a specific portion of a record used for a particular category of data, such as an employee's name or department.\n\nThe records in a data set can be organized in various ways, depending on how we plan to access the information. If you write an application program that processes things like personnel data, for example, your program can define a record format for each person's data.\n\nThere are many different types of data sets in z/OS, and different methods for accessing them. Among the most commonly used types are:\nSequential\nIn a sequential data set, records are data items that are stored consecutively. To retrieve the tenth item in the data set, for example, the system must first pass the preceding nine items. Data items that must all be used in sequence, like the alphabetical list of names in a classroom roster, are best stored in a sequential data set.\nPartitioned\nA partitioned data set or PDS consists of a directory and members. The directory holds the address of each member and thus makes it possible for programs or the operating system to access each member directly. Each member, however, consists of sequentially stored records. Partitioned data sets are often called libraries. Programs are stored as members of partitioned data sets. Generally, the operating system loads the members of a PDS into storage sequentially, but it can access members directly when selecting a program for execution.\nVSAM\nIn a Virtual Storage Access Method (VSAM) key sequenced data set (KSDS), records are data items that are stored with control information (keys) so that the system can retrieve an item without searching all preceding items in the data set. VSAM KSDS data sets are ideal for data items that are used frequently and in an unpredictable order."},
        {"text": "Q: What is a Sequential dataset?\n A: In a sequential data set, records are data items that are stored consecutively. To retrieve the tenth item in the data set, for example, the system must first pass the preceding nine items. Data items that must all be used in sequence, like the alphabetical list of names in a classroom roster, are best stored in a sequential data set."},
        {"text": "Q: When should I use a Sequential data set?\n A: You should use a sequential data set when you need to process records in a specific order, such as when reading through a list of transactions or records that are naturally ordered. Sequential data sets are ideal for batch processing where you read or write records one after another."},
        {"text": "Q: What is a Partitioned dataset?\n A: A partitioned data set or PDS consists of a directory and members. The directory holds the address of each member and thus makes it possible for programs or the operating system to access each member directly. Each member, however, consists of sequentially stored records. Partitioned data sets are often called libraries. Programs are stored as members of partitioned data sets. Generally, the operating system loads the members of a PDS into storage sequentially, but it can access members directly when selecting a program for execution."},
        {"text": "Q: When should I use a Partitioned data set?\n A: You should use a partitioned data set when you need to store multiple related files or members that can be accessed directly. For example, if you have a collection of COBOL programs, you can store each program as a member in a PDS, allowing for easy access and organization."},
        {"text": "Q: What is a VSAM dataset?\n A: In a Virtual Storage Access Method (VSAM) key sequenced data set (KSDS), records are data items that are stored with control information (keys) so that the system can retrieve an item without searching all preceding items in the data set. VSAM KSDS data sets are ideal for data items that are used frequently and in an unpredictable order."},
        {"text": "Q: When should I use a VSAM data set?\n A: You should use a VSAM data set when you need to access records in a non-sequential manner, especially when you have a large dataset and need fast retrieval based on key values. VSAM is commonly used for databases and files that require frequent updates and random access."},
        {"text": "Q: What is a record?\n A: A record is a fixed number of bytes containing data. Often, a record collects related information that is treated as a unit, such as one item in a database or personnel data about one member of a department."},
        {"text": "Q: Explain JCL DD statements.\n A: A DD or data definition statement is used in JCL to define a dataset or file that a program will use. It specifies the dataset name, its attributes (like record format and length), and how it should be accessed (input, output, or both). DD statements can also define temporary datasets or point to existing datasets. They are essential for telling the system where to find the data a program needs or where to write its output."},
        {"text": "Q: What are return codes and how do I use them?\n A: return codes (RCs) are conventionally used to indicate the success or failure of a job step. Programs running within a JCL step set these codes upon termination, following a standard convention. "},
    ]

def generate_cobol_functions_qa():
    """Generate questions about COBOL functions and operations"""
    return [
        {"text": f"Q:How would I get the current date and time in COBOL?\n A: You can use the intrinsic function CURRENT-DATE to get the current date using COBOL. Here is an example of how to use it {load_example_file('example_current_date_cobol.txt')}\n\n."},
        {"text": f"Q:How would I get the mean of a number in COBOL?\nA: You can use the intrisic function MEAN to calculate the mean of a set of numbers in COBOL."},
        {"text": f"Q:How would I get the standard deviation of a set of numbers in COBOL?\nA: You can use the intrinsic function STANDARD-DEVIATION to calculate the standard deviation of a set of numbers in COBOL."},
        {"text": f"Q:In COBOL how do I get the value of PI?\nA: You can use the intrinsic function PI to get the value of π in COBOL."},
        {"text": f"Q:How do I get a random number in COBOL?\nA: You can use the intrinsic function RANDOM to generate a random number in COBOL."},
        {"text": f"Q:How do I reverse a string in COBOL?\nA: You can use the intrinsic function REVERSE to reverse a string in COBOL."},
        {"text": f"Q:How do I calculate the square root of a number in COBOL?\nA: You can use the intrinsic function SQRT to calculate the square root of a number in COBOL."},
        {"text": f"Q:How do I get the absolute value of a number in COBOL?\nA: You can use the intrinsic function ABS to get the absolute value of a number in COBOL."},
        {"text": f"Q:How do I get the remainder of a division in COBOL?\nA: You can use the intrinsic function REM to get the remainder of a division in COBOL."},
    ]

def generate_cobol_code_generation_qa():
    """Generate questions about generating COBOL code"""
    return [
        {"text": f"Q:Create me a COBOL program to calculate the annuity of a loan \n A: Sure! here is an example of a COBOL program that calculates the annuity of a loan {load_example_file('example_annuity_cobol.txt')}\n\n."},
        {'text': f"Q:Create me a COBOL program that writes the current date and time as well as a name\n Here is a simple COBOL program that writes the current date and time along with a name {load_example_file('example_current_date_and_name_COBOL.txt')}\n\n."},
    ]

def generate_jcl_qa():
    """Generate questions about JCL (Job Control Language)"""
    return [
        {"text": f"Q: What is JCL and what is it used for?\n A: Job Control Language (JCL) is a scripting language used on IBM mainframe operating systems (primarily z/OS) to instruct the system on how to run batch jobs, manage datasets, and allocate resources. It acts as the bridge between application programs (like COBOL) and the operating system, defining what program to execute, inputs/outputs required, and the handling of results."},
        {"text": f"Q: Generate me a small sample JCL job to run a COBOL program.\n A: Sure! Here is a simple example of a JCL job that runs a COBOL program {load_example_file('example_easy_JCL.txt')}\n\nWhen submitted for execution:\nMYJOB\nIs a jobname the system associates with this workload.\nMYSORT\nIs the stepname, which instructs the system to execute the SORT program.\nSORTIN\nOn the DD statement, SORTIN is the ddname. The SORTIN ddname is coded in the SORT program as a program input. The data set name (DSN) on this DD statement is ZPROF.AREA.CODES. The data set can be shared (DISP=SHR) with other system processes. The data content of ZPROF.AREA.CODES is SORT program input.\nSORTOUT\nThis ddname is the SORT program output.\nSYSOUT\nSYSOUT=* specifies to send system output messages to the Job Entry Subsystem (JES) print output area. It is possible to send the output to a data set.\nSYSIN\nDD * is another input statement. It specifies that what follows is data or control statements. In this case, it is the sort instruction telling the SORT program which fields of the SORTIN data records are to be sorted."},
        {"text": f"Q: What is a JOB statement?\n A: "},
        {"text": f"Q: What is the EXEC statement?\n A: "},
        {"text": f"Q: What is a DD statement?\n A: "},
        {"text": f"Q: How do I specify dataset location and allocation in JCL?\n A: "},
        {"text": f"Q: What are JCL procedures and how do I use them?\n A: "},
        {"text": f"Q: How do I use conditional execution (COND) in JCL?\n A: "},
        {"text": f"Q: What is the DISP parameter and what are its options?\n A: "},
        {"text": f"Q: How do I pass parameters to programs using JCL?\n A: "},
        {"text": f"Q: What is the difference between IN-STREAM and CATALOGED procedures?\n A: "},
        {"text": f"Q: How do I handle job failure and return codes in JCL?\n A: "},
        {"text": f"Q: Is there a way to make Job A wait for Job B to finish before continuing?\n A: "},
        {"text": f"Q: How do I give my job more memory or space to run a job?\n A: "},
    ]

def generate_jcl_code_generation_qa():
    """Generate questions about generating JCL code"""
    return [
        {"text": f"Q: Create me a simple JCL job to run a COBOL program.\n A: Sure! Here is a simple example of a JCL job that runs a COBOL program {load_example_file('example_JCL_cobol.txt')}\n\n"},
        {"text": f"Q: Create me a JCL job to run a COBOL program that reads from an input dataset and writes to an output dataset.\n A: Here is an example of a JCL job that runs a COBOL program which reads from an input dataset and writes to an output dataset {load_example_file('example_JCL_COBOL_FILEREAD.txt')}\n\n"},
    ]

def generate_cobol_errors_qa():
    """Generate questions about COBOL errors and ABENDs"""
    return [
        {"text": f"Q: What is S0C1 error?\n A: S0C1 is an operation exception. The CPU attempted to execute an invalid or non-existent instruction. In COBOL this commonly happens when a program branches to an incorrect address (such as an uninitialized procedure pointer) or when the load module or called subprogram is corrupt or mismatched. To resolve it, verify that all CALLed programs are present and correctly link-edited, ensure that any procedure or function pointers are initialized before use, and re-link if the load module may be damaged."},
        {"text": f"Q: What is S0C4 error?\n A: S0C4 is an addressing error. The program attempted to access storage it does not own or a misaligned address. In COBOL this is often caused by invalid subscripts or indexes, using reference modification with out-of-range offsets, or corrupting pointers through incorrect CALL arguments. To resolve it, use the dump to identify the failing instruction and data item, check array bounds and reference modifications, turn on bounds-checking or SSRANGE where possible, and correct any logic that drives indexes or pointers outside the allocated storage."},
        {"text": f"Q: What is S0C7 error?\n A: S0C7 is a data exception caused by invalid numeric data in a field that is used in arithmetic or otherwise treated as numeric. Typical causes include spaces or non-numeric characters in a packed-decimal (COMP-3) or zoned-decimal field, or bad group moves overlaying numeric items. To resolve it, locate the failing instruction and the offending field in the dump, validate the input data and any group-level MOVEs, ensure that numeric fields are properly initialized, and add data validation or edit checks before performing arithmetic."},
        {"text": f"Q: What is S0C9 error?\n A: S0C9 is a divide exception. The program attempted an invalid divide operation, such as dividing by zero or producing a quotient too large for the target field. To resolve it, review all DIVIDE statements near the failing instruction, ensure that divisors are checked for zero or invalid values, widen result fields if necessary, and add range checks before performing the division."},
        {"text": f"Q: What is S0CB error?\n A: S0CB is a decimal overflow exception. A decimal arithmetic operation produced a result that could not fit into the target packed or zoned decimal field. To resolve it, examine the arithmetic statement at the failing instruction, increase the size or precision of the target field, or add validation and scaling logic so that intermediate and final results remain within the defined PICTURE ranges."},
        {"text": f"Q: What is U4038 error?\n A: U4038 is a user ABEND frequently issued by Language Environment (LE) when a COBOL run-time condition is not handled. Typical causes include unhandled file status errors, invalid arguments on intrinsic functions, or severe run-time conditions where LE terminates the program. To resolve it, check the LE message text in the job log (CEE3xxx messages) for the underlying condition, correct the COBOL logic or data that caused the error, and optionally enable condition-handling or more detailed LE diagnostics."},
        {"text": f"Q: What is S213 error?\n A: S213 indicates an I/O or dataset access problem. Common causes include a missing dataset, incorrect data set name, catalog problems, or insufficient security authorization for the requested dataset. It can also occur when the dataset is on an unavailable or offline volume. To resolve it, verify the DD statement's DSN, DISP, and volume information, ensure that the dataset exists and is cataloged, check RACF or other security settings for access permissions, and correct any typos or mismatches between the JCL and the actual dataset."},
        {"text": f"Q: What is S013-18 error?\n A: S013-18 is a dataset open error related to record format or length. It usually occurs when the program's FD/LRECL/RECFM does not match the actual dataset attributes, or when the JCL DCB parameters are inconsistent with the COBOL file description. To resolve it, compare the dataset's LRECL, BLKSIZE, and RECFM (from LISTCAT or ISPF 3.4) to the COBOL FD and any DCB parameters in the DD statement, then make them consistent and rerun the job."},
        {"text": f"Q: What is SB37 error?\n A: SB37 is a space allocation error indicating that a sequential dataset ran out of primary and secondary extents on the current volume. This often happens when the output grows larger than anticipated and no more space can be extended. To resolve it, increase the primary and secondary SPACE allocation in the DD statement, choose a unit or volume with more availability, or optimize the program to write less data."},
        {"text": f"Q: What is SD37 error?\n A: SD37 is a space error indicating that a dataset exhausted its primary space and no secondary space was defined. The system cannot extend the dataset further. To resolve it, add a nonzero secondary quantity to the SPACE parameter, increase the primary allocation, or reduce the amount of data written by the program so that it fits within the allocated space."},
        {"text": f"Q: What is SE37 error?\n A: SE37 is a space error indicating that a dataset has reached the maximum number of extents or volumes available. For example, a PDS might reach its 16-extent limit or a multi-volume sequential dataset may have used all allocated volumes. To resolve it, increase the SPACE allocation on fewer but larger volumes, redesign the dataset to require fewer extents (e.g., use a larger primary and smaller secondary), or split the output across multiple datasets."},
        {"text": f"Q: What is S322 error?\n A: S322 indicates that the job or step exceeded its CPU or time limit and was cancelled by the system. This commonly occurs with loops or very long-running jobs where TIME parameters are too restrictive. To resolve it, check for infinite or excessive loops in the COBOL program, optimize expensive processing, and if the logic is correct, increase the TIME or REGION limits in the JCL as appropriate per site standards."},
        {"text": f"Q: What is S522 error?\n A: S522 indicates that a job was cancelled because it was waiting too long for an event such as operator intervention or resource availability. In many shops this arises from jobs waiting at a console prompt or for a tape, mount, or other resource that never arrives. To resolve it, verify that the job does not require manual replies, ensure necessary resources (such as tapes or devices) are available, and consider removing any code that depends on console I/O in batch."},
        {"text": f"Q: What is S806 error?\n A: S806 indicates that the program could not be found in the STEPLIB, JOBLIB, or system linklist libraries. The module named in the JCL EXEC PARM or PROC PGM parameter is not available to be loaded. To resolve it, verify the program name, confirm that the load module is link-edited into a library in the appropriate STEPLIB or JOBLIB concatenation, ensure that the library is cataloged and accessible, and correct any spelling or concatenation errors in the JCL."},
        {"text": f"Q: What is IEC161I error?\n A: IEC161I is a message typically associated with end-of-file and file status issues on QSAM datasets (often paired with ABEND codes). It can appear when a dataset is not opened correctly or when an unexpected end-of-file or I/O condition is reached. To resolve it, check the COBOL file status field after OPEN and READ/WRITE operations, make sure the DD statement correctly defines the dataset, and ensure that the program's record format and length match the dataset attributes."},
        {"text": f"Q: What is IEC130I error?\n A: IEC130I is a dataset attribute error, often indicating an invalid or inconsistent DCB parameter (such as an illegal BLKSIZE or RECFM). It can be associated with S013 abends. To resolve it, correct the DCB parameters on the DD statement, ensure that BLKSIZE is valid for the device and LRECL, and align the JCL definitions with the actual dataset and the COBOL FD."},
    ]

def generate_combined_training_samples():
    """Combine all Q&A categories into training samples"""
    all_samples = []
    
    all_samples.extend(generate_cobol_structure_qa())
    all_samples.extend(generate_mainframe_concepts_qa())
    all_samples.extend(generate_jcl_qa())
    all_samples.extend(generate_cobol_functions_qa())
    all_samples.extend(generate_cobol_code_generation_qa())
    all_samples.extend(generate_jcl_code_generation_qa())
    all_samples.extend(generate_cobol_errors_qa())

    print(len(all_samples))
    return all_samples


if __name__ == "__main__":
    # Generate and display sample training data
    samples = generate_combined_training_samples()
    print(f"Generated {len(samples)} questions\n")
    
    # Show a few examples
    for i, sample in enumerate(samples[:10], 1):
        print(f"Question {i}: {sample['text']}\n")